### ISSUE TITLE
Plugin cannot be installed 

### ISSUE THREAD

**Issue by ThorstenStr** [invenhost/inventree-wled-locator#7]
Hello Matmair,
Thank you very much for the really great work. I would like to use the plugin in my InvenTree installation.
Ubuntu 20.04.6
InvenTree: 0.14.2
Python 3.9.2
Django 4.2.10

but I get the following error when adding it:
inventree_wled_locator cannot import name 'url' from 'django.conf.urls' (/opt/inventree/env/lib/python3.9/site-packages/django/conf/urls/__init__.py)
I have already tested older versions of Django.
Can you help me?
Thank you very much
Thorsten

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/invenhost) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you

<a href="https://polar.sh/invenhost/inventree-wled-locator/issues/7">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/invenhost/inventree-wled-locator/issues/7/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/invenhost/inventree-wled-locator/issues/7/pledge.svg">
</picture>
</a>

**Comment by matmair** [comment]
Hi, I am currently rewriting all of my plugins and processes, not sure when I will have time to revisit this as it is rather low in the number of requests. [See](https://polar.sh/invenhost/posts/plans-for-2024-02)

**Comment by ThorstenStr** [comment]
Hello, thank you very much for the feedback. I would of course be very happy if there will be a future update, to be honest, I only switched to Inventree because of this function. I've been toying with the idea for a long time, I've also participated in one or two crowdfunding projects, but apart from PickbyLight they don't meet my requirements. Inventree is an all-in-one package after all ;)

**Comment by matmair** [comment]
I have added it to the backlog but there is very low interest from the community so no promises on the timeline.

**Comment by PricelessToolkit** [comment]
I'm holding off on updating my server solely because of this module. Currently, I'm using Inventree version "0.12.7" with module version "0.3.0"

**Comment by matmair** [comment]
@ThorstenStr @PricelessToolkit version 0.4.0 should resolve the issues and be available for update on your instances. Please report back if you encounter issues.

@PricelessToolkit thanks for the funding

**Comment by PricelessToolkit** [comment]
Thank you very much! The installation now completes successfully. However, when I click on the locate icon, a new error notification appears: "Error object(xx)." All the configurations, such as IP and LED counts, remain the same. Is there a way to enable a debug mode?

**Comment by PricelessToolkit** [comment]
PS: "Turn off"  from the plugin menu is working!

**Comment by ThorstenStr** [comment]
Hi everyone, thanks for the update on the plugin, I'll do my part tomorrow too ;) 
However, I still can't install it. when I do it via the package name "inventree-wled-locator", I still get the following message:

discovery | inventree_wled_locator | cannot import name 'url' from 'django.conf.urls' (/opt/inventree/env/lib/python3.9/site-packages/django/conf/urls/__init__.py)

It doesn't work via URL either, maybe I'm doing something wrong with the specification?

**Comment by matmair** [comment]
@PricelessToolkit can you post the contents of the error in a new issue? You should get to the detailed traceback by clicking on the notification. If you already marked it as read you can click on the "Show all notifications" button and find it in the "history" section.

**Comment by matmair** [comment]
@ThorstenStr try to restart the server or reload the plugins from the plugins settings.

**Comment by ThorstenStr** [comment]
Hello,
I have restarted invenhost, reinstalled the plugin, then it was initially deactivated:

![grafik](https://github.com/invenhost/inventree-wled-locator/assets/26651869/4d4f7bd9-3ec9-432f-b8c4-3b586653b02b)

After I activated it, the page reloaded and I can no longer access the settings:
![grafik](https://github.com/invenhost/inventree-wled-locator/assets/26651869/03651f77-e4ed-40ee-b9bf-b2ba7eea699b)

**Comment by PricelessToolkit** [comment]
> @PricelessToolkit can you post the contents of the error in a new issue? You should get to the detailed traceback by clicking on the notification. If you already marked it as read you can click on the "Show all notifications" button and find it in the "history" section.

Hi, unfortunately when I click on the error page "http://192.168.40.123/admin/error_report/error/76/change/" it says "This site can’t be reached" When I click on the "Show all notifications" I can see all errors history but I can't open the errors.

**Comment by matmair** [comment]
@PricelessToolkit are you logged in as a superuser? This sounds like you are not an admin or have turned of admin pages fully. Can you open http://192.168.40.123/admin/error_report?

**Comment by PricelessToolkit** [comment]
ok that works!  

````
File "/home/inventree/src/backend/InvenTree/InvenTree/tasks.py", line 212, in offload_task
task.run()

File "/root/.local/lib/python3.11/site-packages/django_q/tasks.py", line 727, in run
self.id = async_task(self.func, *self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django_q/tasks.py", line 70, in async_task
pack = SignedPackage.dumps(task)
^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django_q/signing.py", line 15, in dumps
return signing.dumps(
^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/core/signing.py", line 152, in dumps
return TimestampSigner(key=key, salt=salt).sign_object(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django/core/signing.py", line 250, in sign_object
data = serializer().dumps(obj)
^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/django_q/signing.py", line 35, in dumps
return pickle.dumps(obj, protocol=pickle.HIGHEST_PROTOCOL)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: Can't pickle local object 'View.as_view.<locals>.view'

````
